redis-cli SET key1 "value1"
redis-cli SET key2 "value2"
redis-cli SET key3 "value3"
redis-cli SET key4 "value4"
redis-cli SET key5 "value5"
redis-cli SET key6 "value6"
redis-cli SET key7 "value7"
redis-cli SET key8 "value8"